var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',undefined);
subject.inc(-1,'');
subject.weird('',-1,'','');
subject.weird(8,'','','');
subject.weird('',-1,'','');
subject.weird('','',41,'');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('','pathContent/file1');
mock.restore();
